.gitignore
helm-chart/.helmignore
helm-chart/Chart.yaml
helm-chart/values.yaml

Ref https://github.com/2i2c-org/unnamed-thingity-thing/issues/20

Intial deploy

---

.github/workflows/deploy-production.yaml
.github/workflows/deploy-staging.yaml
.github/workflows/deploy-support.yaml

Add workflows to deploy the staging and prod app

---

helm-charts/app/Chart.yaml
helm-charts/app/prod.values.yaml
helm-charts/app/staging.values.yaml

Add deploy domains to allowed hosts

---

helm-charts/app/prod/prod.values.yaml

Ref https://github.com/2i2c-org/unnamed-thingity-thing/issues/60

Enable plausible.io analytics for the production website

---

helm-charts/app/Chart.yaml
helm-charts/app/prod/prod.values.yaml

- Increase proxy size so we can upload files larger than an mb
- Brings in https://github.com/2i2c-org/unnamed-thingity-thing/pull/67
Ref https://github.com/2i2c-org/unnamed-thingity-thing/issues/59

Add support for media uploads & downloads

---

README.md
deployer.py
helm-charts/app/prod/prod.values.yaml
helm-charts/app/staging/staging.values.yaml
helm-charts/support/Chart.yaml
helm-charts/support/support.values.yaml
helm-charts/support/templates/issuer.yaml

Fixes https://github.com/2i2c-org/unnamed-thingity-thing/issues/61

Add support for https and enable it on both deployments

---

helm-charts/app/prod/prod.values.yaml
helm-charts/app/staging/staging.values.yaml

Until https://github.com/2i2c-org/segmentation-challenge-deploy/issues/27 is fixed.

Replicate site settings prod -> staging

---

deployer.py
helm-charts/app/common.values.yaml
helm-charts/app/prod/prod.values.yaml
helm-charts/app/staging/staging.values.yaml

Add common values config between staging and prod

---

helm-charts/app/Chart.yaml
helm-charts/app/common.values.yaml
helm-charts/app/prod/enc-prod.secret.values.yaml
helm-charts/app/prod/prod.values.yaml
helm-charts/app/staging/enc-staging.secret.values.yaml
helm-charts/app/staging/staging.values.yaml

Related https://github.com/2i2c-org/frx-challenges/pull/148

Rename to FRX challenges

---

helm-charts/app/Chart.yaml
helm-charts/app/charts/frx-challenges/.helmignore

Ref https://github.com/2i2c-org/frx-challenges/pull/195

Bump chart version

---

helm-charts/app/common.values.yaml

Matches what is shown in the README

Switch to using `csc evaluate`

---

helm-charts/app/common.values.yaml

Ref https://github.com/2i2c-org/frx-challenges/issues/190

Update metadata schema and placeholder text

---

helm-charts/app/prod/prod.values.yaml

Fixes https://github.com/2i2c-org/frx-challenges/issues/222

Disable debug mode on prod install

---

helm-charts/app/common.values.yaml

I updated the submission instruction 
but i am not sure about the right schema to use.
Can you please check/merge it?

update submission instructions

---

helm-charts/app/common.values.yaml

Ref: https://2i2c.slack.com/archives/C06RX73KF2R/p1738184013994919

Update terms and conditions

---

helm-charts/app/common.values.yaml
helm-charts/app/prod/prod.values.yaml
helm-charts/app/staging/staging.values.yaml

This replicates staging config to prod, and starts the challenge.

Start the challenge!

---

helm-charts/app/prod/prod.values.yaml

No op change to trigger ci/cd

---

.github/workflows/deploy-production.yaml
.github/workflows/deploy-staging.yaml
helm-charts/app/prod/prod.values.yaml
helm-charts/app/staging/staging.values.yaml

- Fix typo in what triggers prod and staging deployments
- Remove staging overrides that gave things more resources
- Reduce resources given to prod site components too

Cut resources even more

---

helm-charts/app/common.values.yaml

Trying these numbers based on conversation with Jeff.
Also update to use new image for some performance enhancements in the evalator

Update to give the evaluator more resources

---

helm-charts/app/common.values.yaml

You can find the tags from https://quay.io/repository/2i2c/cellmap-segmentation-challenge-evaluator?tab=tags&tag=latest

Bump image used
